// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Ownable2Step, Ownable} from "@openzeppelin/contracts/access/Ownable2Step.sol";
import {IZKCollateral} from "../interfaces/IZKCollateral.sol";

/// @title IGroth16Verifier
/// @notice Interface for the auto-generated Groth16 verifier contract
/// @dev In production, this is generated by snarkjs. For MVP, a MockVerifier is used.
interface IGroth16Verifier {
    /// @notice Verify a Groth16 proof
    /// @param _pA Point A of the proof (2 elements)
    /// @param _pB Point B of the proof (2x2 elements)
    /// @param _pC Point C of the proof (2 elements)
    /// @param _pubSignals Public signals/inputs
    /// @return True if the proof is valid
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[4] calldata _pubSignals
    ) external view returns (bool);
}

/// @title CollateralVerifier
/// @author Xythum Protocol
/// @notice Wraps the Groth16 verifier with protocol-specific logic:
///         - Validates public inputs against on-chain state
///         - Stores verified proofs for lending adapters to reference
///         - Prevents proof replay via nullifier system
/// @dev Uses MockVerifier fallback since circom/snarkjs are not installed.
///      TODO(upgrade): Replace with real Groth16 verifier when circom tooling is available.
contract CollateralVerifier is IZKCollateral, Ownable2Step {
    // ─── Custom Errors ───────────────────────────────────────────────
    error InvalidProof();
    error NullifierAlreadyUsed(bytes32 nullifier);
    error ProofExpired(bytes32 proofId);
    error UnknownAsset(uint256 assetId);
    error ProofNotActive(bytes32 proofId);

    // ─── Events ──────────────────────────────────────────────────────
    event AssetRegistered(address indexed asset, uint256 indexed assetId);
    event ProofInvalidated(bytes32 indexed proofId);

    // ─── Structs ─────────────────────────────────────────────────────
    /// @notice Record of a verified collateral proof
    struct ProofRecord {
        address prover;
        address asset;
        uint256 minimumValue;
        uint256 navPrice;
        uint256 verifiedAt;
        bool active;
    }

    // ─── Immutables ──────────────────────────────────────────────────
    /// @notice The Groth16 verifier contract (auto-generated or mock)
    IGroth16Verifier public immutable verifier;

    // ─── Storage ─────────────────────────────────────────────────────
    /// @notice Mapping from proof ID to proof record
    mapping(bytes32 => ProofRecord) public proofs;

    /// @notice Mapping from nullifier to used status (prevents double-spend)
    mapping(bytes32 => bool) public usedNullifiers;

    /// @notice Asset address to circuit-compatible field element ID
    mapping(address => uint256) public assetIds;

    /// @notice Reverse mapping: field element ID to asset address
    mapping(uint256 => address) public assetAddresses;

    /// @notice Counter for generating unique proof IDs
    uint256 public proofCount;

    // ─── Constructor ─────────────────────────────────────────────────
    /// @param _verifier Address of the Groth16 verifier contract
    /// @param _owner Contract owner
    constructor(address _verifier, address _owner) Ownable(_owner) {
        verifier = IGroth16Verifier(_verifier);
    }

    // ─── External Functions ──────────────────────────────────────────

    /// @inheritdoc IZKCollateral
    /// @dev Public inputs layout: [0]=attestationRoot, [1]=assetId, [2]=minimumValue, [3]=navPrice
    function verifyCollateralProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external override returns (bytes32 proofId) {
        if (publicInputs.length != 4) revert InvalidProof();

        // Extract public inputs
        uint256 assetId = publicInputs[1];
        uint256 minimumValue = publicInputs[2];
        uint256 navPrice = publicInputs[3];

        // Validate asset is registered
        address asset = assetAddresses[assetId];
        if (asset == address(0)) revert UnknownAsset(assetId);

        // Compute nullifier to prevent replay
        bytes32 nullifier = keccak256(proof);
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);
        usedNullifiers[nullifier] = true;

        // Verify the ZK proof via the Groth16 verifier
        bool valid = _verifyGroth16(proof, publicInputs);
        if (!valid) revert InvalidProof();

        // Store proof record
        proofId = keccak256(abi.encode(msg.sender, proofCount++, block.timestamp));
        proofs[proofId] = ProofRecord({
            prover: msg.sender,
            asset: asset,
            minimumValue: minimumValue,
            navPrice: navPrice,
            verifiedAt: block.timestamp,
            active: true
        });

        emit CollateralProofVerified(proofId, asset, minimumValue, block.timestamp);
    }

    /// @inheritdoc IZKCollateral
    function getCollateralValue(bytes32 proofId)
        external view override returns (uint256 minValue, address asset, uint256 timestamp)
    {
        ProofRecord storage record = proofs[proofId];
        return (record.minimumValue, record.asset, record.verifiedAt);
    }

    /// @notice Check if a proof is active
    /// @param proofId The proof identifier
    /// @return True if the proof is active and valid
    function isProofActive(bytes32 proofId) external view returns (bool) {
        return proofs[proofId].active;
    }

    /// @notice Register an asset for use in ZK proofs
    /// @param asset The asset contract address
    /// @param assetId The circuit-compatible field element ID
    function registerAsset(address asset, uint256 assetId) external onlyOwner {
        assetIds[asset] = assetId;
        assetAddresses[assetId] = asset;
        emit AssetRegistered(asset, assetId);
    }

    /// @notice Emergency: invalidate a proof
    /// @param proofId The proof to invalidate
    function invalidateProof(bytes32 proofId) external onlyOwner {
        if (!proofs[proofId].active) revert ProofNotActive(proofId);
        proofs[proofId].active = false;
        emit ProofInvalidated(proofId);
    }

    // ─── Internal ────────────────────────────────────────────────────

    /// @notice Verify a Groth16 proof by decoding proof bytes and calling verifier
    /// @dev Proof format: abi.encode(uint256[2] a, uint256[2][2] b, uint256[2] c)
    ///      TODO(upgrade): Handle actual Groth16 proof format from snarkjs
    function _verifyGroth16(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) internal view returns (bool) {
        // Decode proof into (a, b, c) format
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c
        ) = abi.decode(proof, (uint256[2], uint256[2][2], uint256[2]));

        // Build fixed-size public signals array
        uint256[4] memory pubSignals;
        for (uint256 i = 0; i < 4; i++) {
            pubSignals[i] = publicInputs[i];
        }

        return verifier.verifyProof(a, b, c, pubSignals);
    }
}
