// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { IGroth16Verifier } from "../zk/CollateralVerifier.sol";

/// @title MockGroth16Verifier
/// @author Xythum Protocol
/// @notice Deployable mock Groth16 verifier for testnet deployment.
///         Accepts any proof where public inputs are well-formed.
/// @dev In production, this is replaced with a real Groth16 verifier
///      generated by snarkjs from the circom circuit.
///      TODO(upgrade): Replace with real Groth16 verifier from snarkjs export
contract MockGroth16Verifier is IGroth16Verifier {
    /// @notice If true, all proofs pass. If false, all proofs fail.
    bool public shouldAccept;

    constructor() {
        shouldAccept = true;
    }

    /// @notice Toggle mock verification behavior
    /// @param _accept Whether to accept proofs
    function setShouldAccept(bool _accept) external {
        shouldAccept = _accept;
    }

    /// @inheritdoc IGroth16Verifier
    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[4] calldata
    ) external view override returns (bool) {
        return shouldAccept;
    }
}
